name: Debug run. Book Total Body on next week when push on main branch
on:
  push:
    branches:    
      - main
#   schedule:
#     - cron:  '*/1 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_FIZIKA_EMAIL: ${{ secrets.fizika_email }}
          CYPRESS_FIZIKA_PASSWORD: ${{ secrets.fizika_password }}
          CYPRESS_workout: 'Total'
